table DIM_producto
	lineageTag: b22245e4-d1c1-4708-b34c-e9d12a50098d

	column cod_producto
		dataType: string
		lineageTag: 7839109e-6b19-4e2a-941d-b37c21dbe223
		summarizeBy: none
		sourceColumn: cod_producto

		annotation SummarizationSetBy = Automatic

	column producto
		dataType: string
		lineageTag: d9f585a7-a900-4646-bc33-b5fb8504b0a9
		summarizeBy: none
		sourceColumn: producto

		annotation SummarizationSetBy = Automatic

	column desc_producto
		dataType: string
		lineageTag: 0743ccbd-f42e-4acb-ae3c-422f6314860d
		summarizeBy: none
		sourceColumn: desc_producto

		annotation SummarizationSetBy = Automatic

	column tamanio_pieza_mm
		dataType: string
		lineageTag: 6ac06f1b-e72b-409c-85cd-797f693c46d1
		summarizeBy: none
		sourceColumn: tamanio_pieza_mm

		annotation SummarizationSetBy = Automatic

	column peso_pieza_kg
		dataType: string
		lineageTag: 137cb0bf-326e-4f37-add6-c73b220e0630
		summarizeBy: none
		sourceColumn: peso_pieza_kg

		annotation SummarizationSetBy = Automatic

	partition DIM_producto = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(AzureStorage.BlobContents("https://hernanalmacen.blob.core.windows.net/csv-data/dataset_productos_powerquery.pdf"), [Implementation="1.3"]),
				    Table001 = Origen{[Id="Table001"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Código", type text}, {"Producto", type text}, {"Descripción del producto", type text}, {"Tamaño de la pieza", type text}, {"Peso de la pieza", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado1",{{"Código", "cod_producto"}, {"Producto", "producto"}, {"Descripción del producto", "desc_producto"}, {"Tamaño de la pieza", "tamanio_pieza_mm"}, {"Peso de la pieza", "peso_pieza_kg"}}),
				    #"Texto extraído antes del delimitador" = Table.TransformColumns(#"Columnas con nombre cambiado", {{"tamanio_pieza_mm", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Texto extraído antes del delimitador1" = Table.TransformColumns(#"Texto extraído antes del delimitador", {{"peso_pieza_kg", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Texto extraído después del delimitador" = Table.TransformColumns(#"Texto extraído antes del delimitador1", {{"desc_producto", each Text.AfterDelimiter(_, " -"), type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Texto extraído después del delimitador",{{"desc_producto", Text.Clean, type text}})
				in
				    #"Texto limpio"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

